yahoo/react-stickynode

- Gruntfile.js
- package.json
- src/Sticky.jsx
- tests/functional/bootstrap.js
- tests/unit/Sticky-test.js
> React 14 upgrade

- package.json
- src/Sticky.jsx
> Disable autobind for performance

- README.md
- src/Sticky.jsx
- tests/unit/Sticky-test.js
> More tests

- .eslintignore
- .gitignore
- .travis.yml
- Gruntfile.js
- package.json
- src/Sticky.jsx
- tests/functional/sticky-functional.jsx
- tests/functional/sticky.spec.js
- tests/unit/Sticky-test.js
> update dev dependencies

- package.json
- tests/unit/Sticky-test.js
@src-code @roderickhsiao upgrade dependencies.
> upgrade subscribe-ui-event

- src/Sticky.jsx
@roderickhsiao, make sticky have better precision on height as well.
> better precision on height

- index.js
- src/Sticky.jsx
Minor start for cleaning up syntax
> Align ES6 syntax

- README.md
- src/Sticky.jsx
- tests/unit/Sticky-test.js
> Adds activeClass property

- src/Sticky.jsx
- tests/unit/Sticky-test.js
@kaesonho, before every update, dimensions need to be updated.
> update dimension when props being received

- Gruntfile.js
- package.json
- src/Sticky.jsx
- tests/functional/page.html
@roderickhsiao @redonkulus, upgrade to React@15 and fix warnings.
> explicitly add px unit

- src/Sticky.jsx
@hankhsiao @kaesonho 
minor change
> Change function to es6 syntax

- Gruntfile.js
- package.json
- tests/helpers/rAF.js
- tests/unit/Sticky-test.js
this pr resolves https://github.com/yahoo/react-stickynode/issues/83
> support react16

- README.md
Added a short note which described that we also can use the ES6 import style.
> import like ES6 module

- README.md
- package-lock.json
- src/Sticky.jsx
This allows the component to accept an `innerClass` so that changes can be made to the `innerClass` without having to nest the styles.
I was trying to change the `innerClass` programmatically (on user action) and was having issues, this now works quite well with `innerClass`
> Accept InnerClass

- .github/workflows/node.js.yml
- README.md
> ci: comment out build

- .github/workflows/test.yml
> ci: add GH_TOKEN

- src/Sticky.jsx
> Update on scroll restoration

- .github/workflows/test.yml
> test: deploy keys

- babel.config.json
- package-lock.json
- package.json
- src/Sticky.jsx
- tests/functional/sticky-functional.jsx
- tests/unit/Sticky.test.js
> feat: publish es modules

- package.json
- tests/unit/Sticky.test.js
> feat: support react 18

- .github/workflows/test.yml
- package.json
- src/Sticky.jsx
- tests/functional/index.html
- tests/functional/sticky-functional.jsx
- tests/functional/sticky.spec.js
- tests/unit/Sticky.test.js
> chore: upgrade to latest prettier

- src/Sticky.jsx
> Fix children PropType
