yahoo/react-stickynode

- src/Sticky.jsx
- tests/unit/Sticky-test.js
On server side transform_prop is always transform but on client side on IE and Safari, it's different so we have checksum error.
This fix makes it so that no matter what we show the same transform but depending on the browser the right one will start working.  We'll have little more chars on the mark up but that's not a deal-breaker performance change.
@hankhsiao @src-code
> Fix react checksum error.

- src/Sticky.jsx
For example, an expandable ad creative, is prevented from being hosted in a StickyNode enabled region.
> Remove overflow hidden that prevents expandable contents.

- src/Sticky.jsx
@roderickhsiao the case that sticky is higher then screen should consider sticky top as well.
@codeheroics I think it is the root cause of your jumping issue https://github.com/yahoo/react-stickynode/pull/14. As you can see in the code, there are a lot of hard decision not to make sticky out of boundaries. The bug you found is like some incorrect calculation. Can you help me try your case again after merging this PR.
> fix incorrect calculation of height

- src/Sticky.jsx
@roderickhsiao @codeheroics, the issue was when the sticky's height is bigger then window height, and its bottom is the lowest in document. The root cause is when sticky becomes fixed, the document will collapse, and trigger another condition to make it as the original state.
> set content height to sticky

- src/Sticky.jsx
@roderickhsiao and thank @testerez for finding this issue. This PR is originated from https://github.com/yahoo/react-stickynode/pull/10
> get more precise width

- README.md
- src/Sticky.jsx
I was having bad results using this module with the CSS transforms: my sidebar (longer than the window height) kept flickering on state transitions (original > fixed, fixed > released).
That problem disappeared when I switched off the use of CSS transforms, so this is a PR to allow doing it from the props, even if the browser supports them (the default is still to enable them).
> Allow disabling CSS transforms via props

- Gruntfile.js
- package.json
- src/Sticky.jsx
- tests/unit/Sticky-test.js
@hankhsiao 
now react will throw warning on unitless value, we will probably need to change it as well.
> Upgrade to React 15 and remove shallow compare dependency

- src/Sticky.jsx
@hankhsiao  
fix the issue if users call window.scrollTo directly, 
we will just go to `release` mode and will need to wait for next render to toggle to `fixed` mode 
will have setState twice, but should be ok since it's edge case, 
then we are still going to the flow, `original -> release -> fixed`
> fixed Sticky not being fixed when calling window.scrollTo()

- package.json
- src/Sticky.jsx
- tests/unit/Sticky-test.js
This change allows the sticky behavior to be toggled on and off via the enabled property. We had a use case where a toolbar was desired to be sticky only if a batching function was enabled for a list of items. Setting the enabled prop to true initially would allow the sticky to be toggle; however, without being able to call update or reset, lead to a broken feeling experience.
> Toggling sticky behavior

- src/Sticky.jsx
When `componentWillReceiveProps` happens it calls`updateInitialDimension` to get new dimensions.
However, to calculate these new dimensions, `updateInitialDimension` calls `getTopPosition` and `getBottomBoundary`, which both read information from the old props.
This PR allows an optional object to be passed to `updateInitialDimension` so the new props values can be given to the other functions.
> Allow passing new props to updateInitialDimension

- src/Sticky.jsx
Currently, the `Sticky` ES6 component does not set the displayName explicitly, so its not helpful in the react plugin tab. Adding it to aid debugging.
@kaesonho
> Explicitly add displayName for better debugging

- README.md
- package.json
- src/Sticky.jsx
Adding the ability to temporarily "turn off" a sticky node.  This is intended to be different from the `enabled` prop, which resets the Sticky element - instead, this is a temporary disabling of the component so it doesn't respond to prop changes and scroll/resize events.
Also switching the package used to test for prop and state changes, because `is-equal-shallow` is not suitable for testing props, which includes an object property (`children`) and thus will always cause `isEqual()` to return `false`.  I'm open to using different methods for testing for prop changes however, or eliminating this check altogether if the perf impact isn't significant.
> Adding support for shouldFreeze hook

- src/Sticky.jsx
If a height change has occurred while in "release" mode, a bug will occur since `update()` will rely on an outdated value for `stickyBottom` when deciding whether to fix the stickynode in place.  This fix simply updates the value of `stickyBottom` before using the value for computations.
@roderickhsiao @hankhsiao @alexnj
> Ensuring accurate stickyBottom when in RELEASE mode in case of height change

- src/Sticky.jsx
- tests/unit/Sticky-test.js
@hankhsiao @roderickhsiao @mattho 
Another approach to avoiding the problem of scroll restoration triggering a mis-layout of the sticky node.  In this case, if the current `scrollTop` value matches the cached value during `handleScrollStart()`, we don't update the sticky node.  
Replaces PR #41
> Don't handle scroll if scrollTop value hasn't changed

- README.md
- src/Sticky.jsx
I'm running into some issues with the styles where I need to have a `z-index` defined because I want the content to scroll underneath rather than over it (videoplayers).  This allows us to pass a z for the inner element.
@src-code
> accept props.innerZ to z-index the sticky

- src/Sticky.jsx
Assigning `var self = this;` through the `Sticky.jsx` file served no purpose (and as `self` [is now used in browsers](https://twitter.com/rauschma/status/721992059863896065), it shadowed a global variable)
> Remove use of self instead of this

- src/Sticky.jsx
Addressing issue #45.  Moving the initialization of the globals into `componentDidMount()`.
cc @hankhsiao @lzrski @evgenosiptsov
> Moving globals initialization into componentDidMount()

- package.json
- src/Sticky.jsx
Addressing issue #39.  Making use of `shallowCompare` instead of the buggy `is-equal-shallow`
https://facebook.github.io/react/docs/shallow-compare.html
@hankhsiao @kaesonho @redonkulus
> [issue #39] Switching from is-equal-shallow to React's shallowCompare addon

- README.md
- src/Sticky.jsx
- tests/unit/Sticky-test.js
Thanks for this component. Its super handy!
We ran into a use case where we needed to apply a class to the outer container conditionally when the component was in a released state.
We're using this fork for now, but I'd love to get this merged upstream if it might help anyone else out.
> Add `releasedClass` prop

- package.json
`grunt react` is an nonexistent target. Fixes #52
> Update build target

- .babelrc
Babel will look for config files in parent directories unless you tell it not to. 
This package uses Babel 5 but might be used in projects that use Babel 6 and as such can contain configs what Babel 5 would consider invalid. 
In order to prevent build failures we define a config file for this repo and set it up to tell Babel to stop looking for other config files.
> Add project .babelrc to avoid using root configs

- package.json
- src/Sticky.jsx
To avoid: Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types
package from npm instead.
> style(prop-types): for react 15.5

- README.md
Hopefully I understand the context so that this change makes sense 🤞🏼
> Fixed typo in readme to read more naturally

- package.json
- src/Sticky.jsx
Update refs usage to new api and don't use string refs
https://reactjs.org/docs/refs-and-the-dom.html
"Legacy API: String Refs
If you worked with React before, you might be familiar with an older API where the ref attribute is a string, like "textInput", and the DOM node is accessed as this.refs.textInput. We advise against it because string refs have some issues, are considered legacy, and are likely to be removed in one of the future releases. If you’re currently using this.refs.textInput to access refs, we recommend the callback pattern instead."
> Update refs element usage

- src/Sticky.jsx
translate function can reseive non-integer pos and it causes font smoothing in Chrome (if bottomBoundary element has non-integer height for example). We can call Math.round on pos to prevent it.
> Add Math.round to translate3d

- README.md
I think this makes the README much easier to digest. :)
> Change lists into tables. Correct spelling errors.

- README.md
- src/Sticky.jsx
- tests/unit/Sticky-test.js
I've found that children function support allows to pass sticky state to children components in a very handy way. This approach can be used instead of introducing another wrapper component that will handle state change with `onStateChange` and pass it to children components
> Introduce children function support

- src/Sticky.jsx
Moving to support React async mode: get rid of unsafe componentWillReceiveProps
> Moving to support React async mode: remove unsafe componentWillReceiveProps

- package.json
- tests/unit/Sticky.test.js
---
Adds unit tests to ensure that a regression like #131 should not happen in the future.
Note: The problem on #131 has been resolved in the refactor to `componentDidUpdate` and some more defensive checks in the `getBottomBoundary` method.
Nonetheless, this should help ensure that a similar problem does not happen, by validating that updates to the component, while disabled, do not trigger additional internal updates that are not necessary.
Also, added a jest watch script.
> Unit Tests - ensure that updates gracefully handle enabled=False

- src/Sticky.jsx
Fixes issue were because of debouncing updateInitialDimension is triggered after outerElement is already destroyed.
> Fixes debouncing calls updateInitialDimension after element detroyed

- README.md
- src/Sticky.jsx
Updated the props and documentation with className prop since it is beeing used by the component and therefore can be passed.
In order to can update @types/react-stickynode this should be done before :-)
> added className to component props and updated documentation

- index.js
- package.json
This removes the obsolete `index.js` file and directly sets the `main` field to `dist/Sticky.js` instead.
> Enhance entrypoint in package.json

- README.md
- src/Sticky.jsx
- tests/unit/Sticky.test.js
As requested in https://github.com/yahoo/react-stickynode/issues/275, new prop `innerActiveClass` can now be specified to set a class on the inner element when the sticky state is active.
> Add innerActiveClass prop

- package.json
- tests/unit/Sticky.test.js
> feat: support react 19
